### ISSUE TITLE
Add a ToLoaded method to RemoteData

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE.Meta#8]
It's common to want to transition from Loading to Loading and to map at the same time.

e.g.

1. You have data on the client (D1).
2. You load to get more data (D2)
3. You want to add that data to the current state (D1 + D2).

Loaded D1 -> Loading D1 -> Loaded D1 + D2

The last state transition can be done in code currently as follows:

```fsharp

match data with
| Loading d1 -> Loaded (d1 @ d2)
| other -> other
```

I think we can simplify this pattern:

```fsharp
data |> RemoteData.addData (fun d1 -> d1 @ d2)
```

or maybe

```fsharp
data |> RemoteData.mapToLoaded (fun d1 -> d1 @ d2)
```

What do you think?

**Comment by mattgallagher92** [comment]
Can you give a concrete example? I don't think I've seen that in any apps that I've worked on and I can't imagine why you'd want to combine data into an existing collection, rather than adding into a new collection/replacing an existing one.

I'm leaning towards not doing it as it seems very rare (happy to be proven wrong 🙂) and the benefit to users isn't large.

**Comment by Larocceau** [comment]
I feel similar to Matt about this. I actually think mapping here is a bit risky, since you'll silently lose d2 if d1 is missing. In that case you'd perhaps want an RemoteData.either that maps when needed but initializes the object if there is no data at all?

```fsharp
data |> RemoteData.either ( fun d2 -> [ d2 ] ) ( fun d1 d2 -> d1 @ d2)
```

**Comment by isaacabraham** [comment]
Paging scenarios e.g. Page 1 is loaded and you want to add Page 2 from the server to the client dataset. I suppose this is a kind of "append data" operation really.

But you're both right is that it's a somewhat edge case.

**Comment by isaacabraham** [comment]
And @Larocceau makes a good point - it's clearly not just map, it's something more than that.

**Comment by jwthomson** [comment]
What about something like this? Perhaps badly named though.

```fsharp
    member this.Fold (folder: 'T -> 'T -> 'T) (defaultValue: 'T) (d2: 'T) =
        this.AsOption
        |> Option.defaultValue defaultValue
        |> fun d1 -> folder d1 d2
        |> Loaded
 
```

**Comment by mattgallagher92** [comment]
Without an incredible name, I don't think that it's going to very easy for a developer to know what this function does without checking the implementation. I'd say it's better to just let developers write that code themselves when they need it.

I feel like we're trying to abstract prematurely. I think that we're better off bringing abstractions into this repo after they've emerged from natural usage in our codebases.

My vote is to close this issue.
